#!/usr/bin/env sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#   . Gradle requires a JDK or JRE that is configured properly.
#   . Gradle requires a certain version of Java.
#     Check the wrapper properties file for the required Java version.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`/"$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "`uname`" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

# For Cygwin or MSYS, switch paths to Windows format before running java
if $cygwin || $msys ; then
    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`
    JAVAPATH=`cygpath --path --mixed "$JAVAPATH"`
    if [ -n "$JAVA_HOME" ] ; then
        JAVA_HOME=`cygpath --path --mixed "$JAVA_HOME"`
    fi
fi

# Attempt to set JAVA_HOME
if [ -z "$JAVA_HOME" ] ; then
    JAVA_HOME=`which java`
    if [ -n "$JAVA_HOME" ] ; then
        JAVA_HOME=`dirname "$JAVA_HOME"`
        JAVA_HOME=`dirname "$JAVA_HOME"`
    fi
fi

# For Darwin, add options to specify how the application is bundled.
if $darwin; then
    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin, switch paths to Windows format before running java
if $cygwin; then
    APP_HOME=`cygpath --absolute --mixed "$APP_HOME"`
fi

# Split up the JVM_OPTS into an array, following the shell quoting and substitution rules
function splitJvmOpts() {
    local JVM_OPTS="$1"
    local -a opts
    while [ -n "$JVM_OPTS" ]; do
        local token=""
        local inQuotes=false
        local escapeNext=false
        while [ -n "$JVM_OPTS" ]; do
            local char="${JVM_OPTS:0:1}"
            JVM_OPTS="${JVM_OPTS:1}"
            if $escapeNext; then
                token="$token$char"
                escapeNext=false
            elif [ "$char" = '\\' ]; then
                escapeNext=true
            elif [ "$char" = '"' ]; then
                inQuotes=!$inQuotes
            elif [ "$char" = ' ' ] && !$inQuotes; then
                if [ -n "$token" ]; then
                    opts+=("$token")
                    token=""
                fi
            else
                token="$token$char"
            fi
        done
        if [ -n "$token" ]; then
            opts+=("$token")
        fi
    done
    echo "${opts[@]}"
}

# Use the maximum available, or set MAX_FD != -1 to use that value.
if [ "$MAX_FD" = "maximum" ] ; then
    if $cygwin || $msys ; then
        MAX_FD=`cmd /c "dir /b 2>&1 | findstr /R /C:\"^[0-9]*$\" | sort /R | head -n 1"`
    else
        MAX_FD=`ulimit -H -n`
    fi
fi

if [ "$MAX_FD" = "" ] || [ "$MAX_FD" = "maximum" ] ; then
    MAX_FD="65536"
fi

# Increase the maximum file descriptors if we can
if [ "$MAX_FD" -gt "0" ] 2>/dev/null; then
    ulimit -n "$MAX_FD"
fi

# Collect all arguments for the java command, following the shell quoting and substitution rules
function collectArguments() {
    local -a args
    while [ $# -gt 0 ]; do
        local arg="$1"
        shift
        case "$arg" in
            -D*)
                args+=("$arg")
                ;;
            -X*)
                args+=("$arg")
                ;;
            -XX*)
                args+=("$arg")
                ;;
            *)
                args+=("$arg")
                ;;
        esac
    done
    echo "${args[@]}"
}

# Find the Java binary
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
else
    JAVACMD="java"
fi

if [ ! -x "$JAVACMD" ] ; then
    die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can
if [ "$MAX_FD" -gt "0" ] 2>/dev/null; then
    ulimit -n "$MAX_FD"
fi

# Get the arguments for the java command
GRADLE_OPTS=$(splitJvmOpts "$GRADLE_OPTS")
JAVA_OPTS=$(splitJvmOpts "$JAVA_OPTS")

# Collect all arguments for the java command
GRADLE_ARGS=$(collectArguments "$@")

# Build the classpath
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

# Determine the Java version
JAVA_VERSION=$("$JAVACMD" -version 2>&1 | head -n 1 | cut -d'"' -f2 | cut -d'.' -f1)

# Set appropriate options based on Java version
if [ "$JAVA_VERSION" -ge "9" ] ; then
    JVM_OPTS="$JVM_OPTS --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED"
fi

# For Darwin, add options to specify how the application is bundled.
if $darwin; then
    JVM_OPTS="$JVM_OPTS -Xdock:name=$APP_NAME -Xdock:icon=$APP_HOME/media/gradle.icns"
fi

# Run Gradle
exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain $GRADLE_ARGS
